name: dmg
description: A Flutter package helps you to create, sign, notarize and staple a .DMG with a single command.
version: 0.0.4
homepage: https://github.com/vnniz/dmg
topics:
  - macos
  - tool

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  args: ^2.4.2

dev_dependencies:
  test: ^1.23.0
  flutter_lints: ^2.0.0

platforms:
  macos:
