name: dmg
description: A Flutter package that helps you create, sign, notarize, and staple a .DMG with a single command.
version: 0.1.0
homepage: https://github.com/lamnhan066/dmg
topics:
  - macos
  - dmg
  - sign
  - notarize
  - staple

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  args: ^2.4.2

dev_dependencies:
  test: ^1.25.0
  flutter_lints: ^5.0.0

platforms:
  macos:
